<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>653d2df2-90f9-4099-8bc5-ce2a3bd2b067</UserSecretsId>
    <SkipValidateAspireHostProjectResources>true</SkipValidateAspireHostProjectResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
  </ItemGroup>

  <!-- ERP.Gateway -->
  <ItemGroup>
    <ProjectReference Include="../ERP.Gateway/ERP.Gateway.csproj" />
  </ItemGroup>

  <!-- 受訓證件作業 -->
  <ItemGroup>
    <ProjectReference Include="../../src/TCS.Web/TCS.Web.csproj" />
  </ItemGroup>

</Project>
