// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCS.Infrastructure.Data;

#nullable disable

namespace TCS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCS.Core.Entities.Employee", b =>
                {
                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MV004");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MV001")
                        .IsFixedLength(false);

                    b.Property<string>("HireDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MV021")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MV002");

                    b.ToTable((string)null);

                    b.ToView("CMSMV", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.LicenseMaster", b =>
                {
                    b.Property<string>("LicenseType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MA001")
                        .IsFixedLength(false);

                    b.Property<string>("Category")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MA003")
                        .IsFixedLength(false);

                    b.Property<string>("Company")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COMPANY");

                    b.Property<string>("CreateDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("CREATE_DATE")
                        .IsFixedLength();

                    b.Property<string>("Creator")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CREATOR")
                        .IsFixedLength(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MA002");

                    b.Property<decimal?>("Flag")
                        .HasColumnType("decimal(3,0)")
                        .HasColumnName("FLAG");

                    b.Property<int?>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("MA004");

                    b.Property<string>("ModiDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MODI_DATE")
                        .IsFixedLength();

                    b.Property<string>("Modifier")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MODIFIER")
                        .IsFixedLength(false);

                    b.Property<string>("UsrGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("USR_GROUP");

                    b.Property<int?>("Years")
                        .HasColumnType("int")
                        .HasColumnName("MA005");

                    b.HasKey("LicenseType");

                    b.ToTable("TCSMA", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.LicensePlantRequirement", b =>
                {
                    b.Property<string>("LicenseType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MB001")
                        .IsFixedLength(false);

                    b.Property<string>("Plant")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("MB002")
                        .IsFixedLength();

                    b.Property<string>("Company")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COMPANY");

                    b.Property<string>("CreateDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("CREATE_DATE")
                        .IsFixedLength();

                    b.Property<string>("Creator")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CREATOR")
                        .IsFixedLength(false);

                    b.Property<decimal?>("Flag")
                        .HasColumnType("decimal(3,0)")
                        .HasColumnName("FLAG");

                    b.Property<string>("ModiDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MODI_DATE")
                        .IsFixedLength();

                    b.Property<string>("Modifier")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MODIFIER")
                        .IsFixedLength(false);

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int")
                        .HasColumnName("MB003");

                    b.Property<string>("UsrGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("USR_GROUP");

                    b.HasKey("LicenseType", "Plant");

                    b.ToTable("TCSMB", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.Plant", b =>
                {
                    b.Property<string>("PlantCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("MB001")
                        .IsFixedLength();

                    b.Property<string>("PlantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MB002");

                    b.ToTable((string)null);

                    b.ToView("CMSMB", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.TrainingDetail", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TB001")
                        .IsFixedLength(false);

                    b.Property<string>("LicenseType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TB002")
                        .IsFixedLength(false);

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("date")
                        .HasColumnName("TB003");

                    b.Property<string>("Company")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COMPANY");

                    b.Property<string>("CreateDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("CREATE_DATE")
                        .IsFixedLength();

                    b.Property<string>("Creator")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CREATOR")
                        .IsFixedLength(false);

                    b.Property<decimal?>("Flag")
                        .HasColumnType("decimal(3,0)")
                        .HasColumnName("FLAG");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("TB005");

                    b.Property<string>("ModiDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MODI_DATE")
                        .IsFixedLength();

                    b.Property<string>("Modifier")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MODIFIER")
                        .IsFixedLength(false);

                    b.Property<int>("TrainingType")
                        .HasColumnType("int")
                        .HasColumnName("TB004");

                    b.Property<string>("UsrGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("USR_GROUP");

                    b.HasKey("EmployeeId", "LicenseType", "TrainingDate");

                    b.ToTable("TCSTB", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.TrainingHeader", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TA001")
                        .IsFixedLength(false);

                    b.Property<string>("LicenseType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TA002")
                        .IsFixedLength(false);

                    b.Property<string>("Company")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COMPANY");

                    b.Property<string>("CreateDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("CREATE_DATE")
                        .IsFixedLength();

                    b.Property<string>("Creator")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CREATOR")
                        .IsFixedLength(false);

                    b.Property<decimal?>("Flag")
                        .HasColumnType("decimal(3,0)")
                        .HasColumnName("FLAG");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("TA004");

                    b.Property<string>("ModiDate")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MODI_DATE")
                        .IsFixedLength();

                    b.Property<string>("Modifier")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MODIFIER")
                        .IsFixedLength(false);

                    b.Property<string>("Plant")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("TA003")
                        .IsFixedLength();

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TA005");

                    b.Property<string>("UsrGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("USR_GROUP");

                    b.Property<int?>("Years")
                        .HasColumnType("int")
                        .HasColumnName("TA006");

                    b.HasKey("EmployeeId", "LicenseType");

                    b.HasIndex("LicenseType")
                        .HasDatabaseName("IX_TCSTA_LicenseType");

                    b.ToTable("TCSTA", (string)null);
                });

            modelBuilder.Entity("TCS.Core.Entities.LicensePlantRequirement", b =>
                {
                    b.HasOne("TCS.Core.Entities.LicenseMaster", "LicenseMasterNav")
                        .WithMany("PlantRequirements")
                        .HasForeignKey("LicenseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseMasterNav");
                });

            modelBuilder.Entity("TCS.Core.Entities.TrainingDetail", b =>
                {
                    b.HasOne("TCS.Core.Entities.TrainingHeader", null)
                        .WithMany("Details")
                        .HasForeignKey("EmployeeId", "LicenseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TCS.Core.Entities.TrainingHeader", b =>
                {
                    b.HasOne("TCS.Core.Entities.LicenseMaster", "LicenseMasterNav")
                        .WithMany("TrainingHeaders")
                        .HasForeignKey("LicenseType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LicenseMasterNav");
                });

            modelBuilder.Entity("TCS.Core.Entities.LicenseMaster", b =>
                {
                    b.Navigation("PlantRequirements");

                    b.Navigation("TrainingHeaders");
                });

            modelBuilder.Entity("TCS.Core.Entities.TrainingHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
